### ISSUE TITLE
Auth::user() problem

### ISSUE THREAD

**Issue by diegoscunha** [robsontenorio/laravel-keycloak-guard#31] opened 2020-09-24 17:33 UTC
Hello I have a problem with laravel-keycloak-guard.
Everything seems to be going smoothly, but when I try to access user data via \ Auth :: user () it returns an empty user object.
I would like to know that if my KEYCLOAK_LOAD_USER_FROM_DATABASE variable is set to false, the user object is not loaded with the user data contained in the sent token?

**Comment by robsontenorio** [comment] 2020-09-24 17:41
This is a intended behavior, usefull when  you dont have a `users` table.

The autenticated user will be a empty user.

https://github.com/robsontenorio/laravel-keycloak-guard/blob/c05feebe7d60104dada8246b0c5268f52bd9967c/src/KeycloakGuard.php#L126-L137


If you enable `KEYCLOAK_APPEND_DECODED_TOKEN=true`, then `Auth::user()` will give you a `User` object with token info.

**Comment by diegoscunha** [comment] 2020-09-24 19:47
Thank you.
But, anyway, I will need to get user data through an API.

**Comment by robsontenorio** [comment] 2020-09-24 20:58
In this case I advise you to revisit keycloak concepts, because this question is out of scope.

**Closed** 2020-10-09 13:32 UTC
